VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IChkDskSink"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Sub Done(ByRef bError As Boolean)

End Sub
Public Sub Progress(ByVal lNewValue As Long, ByRef bCancel As Boolean)
    
End Sub
Public Sub Status(ByVal sValue As String, ByRef bCancel As Boolean)
    
End Sub
